version: '3.9'
services:
  app:
    container_name: golang_container
    tty: true
    build: ./
    command: ./app
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - postgresdb
    networks:
      - forsn
      
  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    ports:
      - '5435:5432'
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - forsn

volumes:
  pg_data:


# Networks to be created to facilitate communication between containers
networks:
  forsn:
    driver: bridge